/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangunruangteam2;

/**
 *
 * @author ACER
 */
public class FrameTabung extends javax.swing.JFrame {

    /**
     * Creates new form FrameTabung
     */
    public FrameTabung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_Judul = new javax.swing.JLabel();
        label_TeksJarijari = new javax.swing.JLabel();
        label_TeksJarijari1 = new javax.swing.JLabel();
        tf_Tinggi = new javax.swing.JTextField();
        tf_Jarijari = new javax.swing.JTextField();
        button_Hitung = new javax.swing.JButton();
        panel_Output = new javax.swing.JPanel();
        label_TeksVolume = new javax.swing.JLabel();
        label_TeksLuasPermukaan = new javax.swing.JLabel();
        tf_LuasPermukaan = new javax.swing.JTextField();
        tf_Volume = new javax.swing.JTextField();
        button_Kembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        label_Judul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        label_Judul.setForeground(new java.awt.Color(255, 255, 255));
        label_Judul.setText("BANGUN RUANG ALAS PERSEGI");

        label_TeksJarijari.setBackground(new java.awt.Color(242, 242, 242));
        label_TeksJarijari.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_TeksJarijari.setForeground(new java.awt.Color(255, 255, 255));
        label_TeksJarijari.setText("JARI-JARI");

        label_TeksJarijari1.setBackground(new java.awt.Color(242, 242, 242));
        label_TeksJarijari1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_TeksJarijari1.setForeground(new java.awt.Color(255, 255, 255));
        label_TeksJarijari1.setText("TINGGI");

        tf_Tinggi.setBackground(new java.awt.Color(255, 255, 255));
        tf_Tinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_TinggiActionPerformed(evt);
            }
        });

        tf_Jarijari.setBackground(new java.awt.Color(255, 255, 255));
        tf_Jarijari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_JarijariActionPerformed(evt);
            }
        });

        button_Hitung.setBackground(new java.awt.Color(255, 255, 255));
        button_Hitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button_Hitung.setForeground(new java.awt.Color(255, 0, 0));
        button_Hitung.setText("HITUNG");
        button_Hitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_HitungActionPerformed(evt);
            }
        });

        panel_Output.setBackground(new java.awt.Color(204, 204, 204));
        panel_Output.setForeground(new java.awt.Color(0, 0, 0));
        panel_Output.setToolTipText("OUTPUT");
        panel_Output.setName(""); // NOI18N

        label_TeksVolume.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_TeksVolume.setForeground(new java.awt.Color(0, 0, 0));
        label_TeksVolume.setText("VOLUME");

        label_TeksLuasPermukaan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_TeksLuasPermukaan.setForeground(new java.awt.Color(0, 0, 0));
        label_TeksLuasPermukaan.setText("LUAS PERMUKAAN");

        tf_LuasPermukaan.setBackground(new java.awt.Color(255, 255, 255));
        tf_LuasPermukaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_LuasPermukaanActionPerformed(evt);
            }
        });

        tf_Volume.setBackground(new java.awt.Color(255, 255, 255));
        tf_Volume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_VolumeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_OutputLayout = new javax.swing.GroupLayout(panel_Output);
        panel_Output.setLayout(panel_OutputLayout);
        panel_OutputLayout.setHorizontalGroup(
            panel_OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_OutputLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel_OutputLayout.createSequentialGroup()
                        .addComponent(label_TeksLuasPermukaan)
                        .addGap(18, 18, 18)
                        .addComponent(tf_LuasPermukaan))
                    .addGroup(panel_OutputLayout.createSequentialGroup()
                        .addComponent(label_TeksVolume)
                        .addGap(88, 88, 88)
                        .addComponent(tf_Volume, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_OutputLayout.setVerticalGroup(
            panel_OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_OutputLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(panel_OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_TeksVolume)
                    .addComponent(tf_Volume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_OutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_LuasPermukaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_TeksLuasPermukaan))
                .addGap(49, 49, 49))
        );

        button_Kembali.setBackground(new java.awt.Color(255, 255, 255));
        button_Kembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        button_Kembali.setForeground(new java.awt.Color(255, 0, 0));
        button_Kembali.setText("KEMBALI");
        button_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_KembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panel_Output, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_TeksJarijari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(tf_Jarijari, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(button_Kembali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(button_Hitung))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(label_TeksJarijari1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_Tinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(label_Judul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(label_Judul, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Jarijari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_TeksJarijari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_Tinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_TeksJarijari1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_Hitung)
                    .addComponent(button_Kembali))
                .addGap(28, 28, 28)
                .addComponent(panel_Output, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Output.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tf_TinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_TinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_TinggiActionPerformed

    private void tf_JarijariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_JarijariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_JarijariActionPerformed

    private void tf_LuasPermukaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_LuasPermukaanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_LuasPermukaanActionPerformed

    private void tf_VolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_VolumeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_VolumeActionPerformed

    private void button_HitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_HitungActionPerformed
        tabungAngga TA = new tabungAngga();
        
        TA.setJariJari(Double.parseDouble(tf_Jarijari.getText()));
        TA.setTinggi(Double.parseDouble(tf_Tinggi.getText()));
        
        TA.setVolume();
        TA.setLuasPermukaan();
        
        tf_Volume.setText(String.valueOf(TA.setVolume()));
        tf_LuasPermukaan.setText(String.valueOf(TA.setLuasPermukaan()));
    }//GEN-LAST:event_button_HitungActionPerformed

    private void button_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_KembaliActionPerformed
        dispose();
    }//GEN-LAST:event_button_KembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameTabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameTabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameTabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameTabung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameTabung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_Hitung;
    private javax.swing.JButton button_Kembali;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label_Judul;
    private javax.swing.JLabel label_TeksJarijari;
    private javax.swing.JLabel label_TeksJarijari1;
    private javax.swing.JLabel label_TeksLuasPermukaan;
    private javax.swing.JLabel label_TeksVolume;
    private javax.swing.JPanel panel_Output;
    private javax.swing.JTextField tf_Jarijari;
    private javax.swing.JTextField tf_LuasPermukaan;
    private javax.swing.JTextField tf_Tinggi;
    private javax.swing.JTextField tf_Volume;
    // End of variables declaration//GEN-END:variables
}
