/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangunruangteam2;

/**
 *
 * @author user
 */
public class frameBola extends javax.swing.JFrame {

    /**
     * Creates new form frameBola
     */
    public frameBola() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUtama = new javax.swing.JPanel();
        lBangunRuang = new javax.swing.JLabel();
        lJari = new javax.swing.JLabel();
        tJari = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        pOutput = new javax.swing.JPanel();
        lVolume = new javax.swing.JLabel();
        lLuas = new javax.swing.JLabel();
        vVolume = new javax.swing.JTextField();
        vLuas = new javax.swing.JTextField();
        bKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pUtama.setBackground(new java.awt.Color(0, 153, 153));

        lBangunRuang.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lBangunRuang.setForeground(new java.awt.Color(255, 255, 255));
        lBangunRuang.setText("Bangun Ruang Bola");

        lJari.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lJari.setForeground(new java.awt.Color(255, 255, 255));
        lJari.setText("Jari Jari     :");

        bHitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHitung.setForeground(new java.awt.Color(255, 0, 0));
        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        pOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        lVolume.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lVolume.setText("Volume :");

        lLuas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lLuas.setText("Luas      :");

        javax.swing.GroupLayout pOutputLayout = new javax.swing.GroupLayout(pOutput);
        pOutput.setLayout(pOutputLayout);
        pOutputLayout.setHorizontalGroup(
            pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOutputLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pOutputLayout.createSequentialGroup()
                        .addComponent(lLuas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pOutputLayout.createSequentialGroup()
                        .addComponent(lVolume)
                        .addGap(18, 18, 18)
                        .addComponent(vVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pOutputLayout.setVerticalGroup(
            pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOutputLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lVolume)
                    .addComponent(vVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLuas)
                    .addComponent(vLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        bKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bKembali.setForeground(new java.awt.Color(255, 0, 51));
        bKembali.setText("Kembali");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pUtamaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bKembali)
                .addGap(18, 18, 18)
                .addComponent(bHitung)
                .addGap(115, 115, 115))
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lJari)
                        .addGap(60, 60, 60)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tJari, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lBangunRuang)))
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(pOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lBangunRuang)
                .addGap(46, 46, 46)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tJari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lJari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bKembali)
                    .addComponent(bHitung))
                .addGap(61, 61, 61)
                .addComponent(pOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
       
    bolaAzik bn = new bolaAzik();

    double jari = Double.parseDouble(tJari.getText());

    bn.setJariJari(jari);
    
    double volume = bn.setVolume();
    double luas = bn.setLuasPermukaan();

    vVolume.setText(String.valueOf(volume));
    vLuas.setText(String.valueOf(luas));
    }//GEN-LAST:event_bHitungActionPerformed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_bKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameBola.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameBola().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bKembali;
    private javax.swing.JLabel lBangunRuang;
    private javax.swing.JLabel lJari;
    private javax.swing.JLabel lLuas;
    private javax.swing.JLabel lVolume;
    private javax.swing.JPanel pOutput;
    private javax.swing.JPanel pUtama;
    private javax.swing.JTextField tJari;
    private javax.swing.JTextField vLuas;
    private javax.swing.JTextField vVolume;
    // End of variables declaration//GEN-END:variables
}
