/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bangunruangteam2;

/**
 *
 * @author Nabila
 */
public class frameBalok extends javax.swing.JFrame {

    /**
     * Creates new form frameBalok
     */
    public frameBalok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pUtama = new javax.swing.JPanel();
        lBangunRuang = new javax.swing.JLabel();
        lPanjang = new javax.swing.JLabel();
        lLebar = new javax.swing.JLabel();
        lTinggi = new javax.swing.JLabel();
        tLebar = new javax.swing.JTextField();
        tPanjang = new javax.swing.JTextField();
        tTinggi = new javax.swing.JTextField();
        bHitung = new javax.swing.JButton();
        pOutput = new javax.swing.JPanel();
        lVolume = new javax.swing.JLabel();
        lLuas = new javax.swing.JLabel();
        vVolume = new javax.swing.JTextField();
        vLuas = new javax.swing.JTextField();
        bKembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pUtama.setBackground(new java.awt.Color(0, 153, 153));

        lBangunRuang.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lBangunRuang.setForeground(new java.awt.Color(255, 255, 255));
        lBangunRuang.setText("Bangun Ruang Balok");

        lPanjang.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lPanjang.setForeground(new java.awt.Color(255, 255, 255));
        lPanjang.setText("Panjang :");

        lLebar.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lLebar.setForeground(new java.awt.Color(255, 255, 255));
        lLebar.setText("Lebar    :");

        lTinggi.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lTinggi.setForeground(new java.awt.Color(255, 255, 255));
        lTinggi.setText("Tinggi   :");

        bHitung.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bHitung.setForeground(new java.awt.Color(255, 0, 0));
        bHitung.setText("Hitung");
        bHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHitungActionPerformed(evt);
            }
        });

        pOutput.setBorder(javax.swing.BorderFactory.createTitledBorder("Output"));

        lVolume.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lVolume.setText("Volume :");

        lLuas.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lLuas.setText("Luas      :");

        javax.swing.GroupLayout pOutputLayout = new javax.swing.GroupLayout(pOutput);
        pOutput.setLayout(pOutputLayout);
        pOutputLayout.setHorizontalGroup(
            pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOutputLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pOutputLayout.createSequentialGroup()
                        .addComponent(lLuas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vLuas, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pOutputLayout.createSequentialGroup()
                        .addComponent(lVolume)
                        .addGap(18, 18, 18)
                        .addComponent(vVolume, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pOutputLayout.setVerticalGroup(
            pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pOutputLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lVolume)
                    .addComponent(vVolume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pOutputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lLuas)
                    .addComponent(vLuas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        bKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bKembali.setForeground(new java.awt.Color(255, 0, 51));
        bKembali.setText("Kembali");
        bKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUtamaLayout = new javax.swing.GroupLayout(pUtama);
        pUtama.setLayout(pUtamaLayout);
        pUtamaLayout.setHorizontalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(lBangunRuang))
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tLebar, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pUtamaLayout.createSequentialGroup()
                                .addComponent(bKembali)
                                .addGap(18, 18, 18)
                                .addComponent(bHitung))))
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lLebar)
                            .addComponent(lPanjang)
                            .addComponent(lTinggi)
                            .addComponent(pOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pUtamaLayout.setVerticalGroup(
            pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUtamaLayout.createSequentialGroup()
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lPanjang)
                            .addComponent(tPanjang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lLebar)
                            .addComponent(tLebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pUtamaLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lBangunRuang)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTinggi)
                    .addComponent(tTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bHitung)
                    .addComponent(bKembali))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHitungActionPerformed
        balokNabilaa bn = new balokNabilaa();
        
        bn.setPanjang(Double.parseDouble(tPanjang.getText()));
        bn.setLebar(Double.parseDouble(tLebar.getText()));
        bn.setTinggi(Double.parseDouble(tTinggi.getText()));
        
        bn.setVolume();
        bn.setLuasPermukaan();
        
        vVolume.setText(String.valueOf(bn.setVolume()));
        vLuas.setText(String.valueOf(bn.setLuasPermukaan()));

    }//GEN-LAST:event_bHitungActionPerformed

    private void bKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_bKembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameBalok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameBalok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameBalok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameBalok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frameBalok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bHitung;
    private javax.swing.JButton bKembali;
    private javax.swing.JLabel lBangunRuang;
    private javax.swing.JLabel lLebar;
    private javax.swing.JLabel lLuas;
    private javax.swing.JLabel lPanjang;
    private javax.swing.JLabel lTinggi;
    private javax.swing.JLabel lVolume;
    private javax.swing.JPanel pOutput;
    private javax.swing.JPanel pUtama;
    private javax.swing.JTextField tLebar;
    private javax.swing.JTextField tPanjang;
    private javax.swing.JTextField tTinggi;
    private javax.swing.JTextField vLuas;
    private javax.swing.JTextField vVolume;
    // End of variables declaration//GEN-END:variables
}
